{
 "title": "Application",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "User conversion",
   "type": "graph",
   "description": "Number of pro and free users on 1interviewparjour.com",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pro_user" },
    { "expr": "not_pro_user" }
   ]
  },
  {
   "title": "Landing pages tracking",
   "type": "graph",
   "description": "Number of requests to a landing page",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "http_request_total{endpoint=\"tracking/landing_page/home\",method=\"GET\"}"
    },
    {
     "expr": "http_request_total{endpoint=\"tracking/landing_page/introduction\",method=\"GET\"}"
    },
    {
     "expr": "http_request_total{endpoint=\"tracking/landing_page/method\",method=\"GET\"}"
    },
    {
     "expr": "http_request_total{endpoint=\"tracking/landing_page/example\",method=\"GET\"}"
    },
    {
     "expr": "http_request_total{endpoint=\"tracking/landing_page/pro\",method=\"GET\"}"
    }
   ]
  },
  {
   "title": "Mailing process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mail_sent{sending_type=\"batch\"}"
    },
    {
     "expr": "mail_sent{sending_type=\"unit\"}"
    }
   ]
  },
  {
   "title": "Planning tracking",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_total{endpoint=\"planning/fetch_planning\",method=\"GET\"}"
    },
    {
     "expr": "http_request_total{endpoint=\"planning/save_planning\",method=\"POST\"}"
    }
   ]
  },
  {
   "title": "Model creattion",
   "type": "graph",
   "description": "How many DB models are created",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "model_inserts_total{model=\"user\"}"
    },
    {
     "expr": "model_inserts_total{model=\"problem\"}"
    },
    {
     "expr": "model_inserts_total{model=\"planningEvent\"}"
    }
   ]
  },
  {
   "title": "Stripe payments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_total{endpoint=\"stripe/success\",method=\"GET\"}"
    },
    {
     "expr": "http_request_total{endpoint=\"stripe/cancelled\",method=\"GET\"}"
    },
    {
     "expr": "http_request_total{endpoint=\"stripe/create-checkout-session\",method=\"GET\"}"
    },
    {
     "expr": "http_request_total{endpoint=\"stripe/create-checkout-session-from-lp\",method=\"GET\"}"
    }
   ]
  }
 ]
}