# Generated by Django 3.1 on 2020-09-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0004_auto_20200921_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text="The Stripe product_id. Something like 'prod_zefaXSszaf...'", max_length=255),
        ),
    ]
