# Generated by Django 3.1 on 2020-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0009_auto_20200921_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='recurring_interval',
            field=models.CharField(blank=True, choices=[(None, None), ('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='month', help_text='Type of the recurring interval.', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='recurring_interval_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='price',
            name='recurring_usage_type',
            field=models.CharField(blank=True, choices=[(None, None), ('licensed', 'licensed'), ('metered', 'metered')], default='licensed', help_text='Usage type of the recurring payment. For us its only LICENSED.', max_length=20),
        ),
    ]
