# Generated by Django 3.1 on 2020-08-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylogo',
            name='name',
            field=models.CharField(default='1interviewparjour', max_length=250),
        ),
    ]
