export const VERIFY_IDENTITY = 'VERIFY_IDENTITY'
export const VERIFY_IDENTITY_SUCCESS = 'VERIFY_IDENTITY_SUCCESS'
export const VERIFY_IDENTITY_ERROR = 'VERIFY_IDENTITY_ERROR'

export const SEND_PRODUCT = 'SEND_PRODUCT'
export const SEND_PRODUCT_SUCCESS = 'SEND_PRODUCT_SUCCESS'
export const SEND_PRODUCT_ERROR = 'SEND_PRODUCT_ERROR'
