version: '3'

services:
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: oneinterviewparjour
            MYSQL_ROOT_PASSWORD: oneinterviewparjour
            MYSQL_USER: oneinterviewparjour
            MYSQL_PASSWORD: oneinterviewparjour
        ports:
            - "3306:3306"
        volumes:
            - "./db:/var/lib/mysql"
    redis:
        image: 'bitnami/redis:5.0'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6379:6379'
        volumes:
            - './redis-volume/data:/bitnami/redis/data'
        command: /opt/bitnami/scripts/redis/run.sh --maxmemory 200mb --maxmemory-policy allkeys-lru