pipeline {
    agent any

    stages {
        stage('Dockerfiles credentials bash templating') {
            steps {
                withCredentials([
                    string(credentialsId: 'dd0d0766-4a8a-49b6-8368-b426bdfbcdeb', variable: 'APP_ROLE_ID'),
                    string(credentialsId: '6a3d47dd-06ed-4612-aaf1-aece42f9713f', variable: 'APP_ROLE_SECRET_ID')
                ]) {
                    echo "> Injecting Vault AppRole into docker/ci/env/backend.env ..."
                    sh "cd docker/ci/env && sed -e 's/\${approle_id}/${APP_ROLE_ID}/' -e 's/\${approle_secret_id}/${APP_ROLE_SECRET_ID}/' backend.env > backend-temp.env && rm backend.env && cat backend-temp.env > backend.env && rm backend-temp.env"
                }
            }
        }
        stage('Deployment') {
            steps {
                echo "> Exposing Vault address ..."
                sh "export VAULT_ADDR=http://127.0.0.1:8200"
                echo "> Updating/Creating the application stack ..."
                sh "cd docker/ci && ./update-stack.sh"
            }
        }
    }
}