pipeline {
    agent any

    stages {
        /*
        stage('Checkout Git') {
            steps {
                echo '> Checking out the source control ...'
                checkout scm
            }
        }
        stage('Git Pull') {
            steps {
                echo '> Pulling the code from GitHub repository ...'
                sh 'git remote update && git checkout master && git pull origin master'
            }
        }
        */
        stage('Dockerfiles bash templating') {
            steps {
                withCredentials([
                    string(credentialsId: 'dd0d0766-4a8a-49b6-8368-b426bdfbcdeb', variable: 'APP_ROLE_ID'),
                    string(credentialsId: '6a3d47dd-06ed-4612-aaf1-aece42f9713f', variable: 'APP_ROLE_SECRET_ID')
                ]) {
                    echo "> Injecting Vault AppRole into docker/ci/web/Dockerfile ..."
                    sh "cd docker/ci/web && sed -e 's/\${approle_id}/$APP_ROLE_ID/' -e 's/\${approle_secret_id}/$APP_ROLE_SECRET_ID/' Dockerfile &> Dockerfile-temp && rm Dockerfile && cat Dockerfile-temp &> Dockerfile"
                    echo "> Injecting Vault AppRole into docker/ci/1interviewparjour/Dockerfile ..."
                    sh "cd docker/ci/1interviewparjour && sed -e 's/\${approle_id}/$APP_ROLE_ID/' -e 's/\${approle_secret_id}/$APP_ROLE_SECRET_ID/' Dockerfile &> Dockerfile-temp && rm Dockerfile && cat Dockerfile-temp &> Dockerfile"
                }
            }
        }
        stage('Showing Dockerfiles content') {
            steps {
                sh "pwd"
                echo "> showing docker/ci/web/Dockerfile ..."
                sh "cat docker/ci/web/Dockerfile"
                sh "cat docker/ci/web/Dockerfile-temp"
                /*
                echo "> showing docker/ci/1interviewparjour/Dockerfile ..."
                sh "cat docker/ci/1interviewparjour/Dockerfile"
                sh "cat docker/ci/1interviewparjour/Dockerfile-temp"
                sh "pwd"
                */
            }
        }
    }
}