# Generated by Django 3.1 on 2020-08-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField()),
                ('correction', models.TextField()),
                ('difficulte', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=250)),
                ('pro', models.BooleanField(default=False)),
                ('inscription_timestamp', models.DateTimeField(auto_now_add=True)),
                ('deinscription_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.IntegerField()),
                ('id_pb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.problem')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
