# Generated by Django 3.1 on 2020-09-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0012_delete_buyinghash'),
        ('core', '0002_auto_20200918_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe.price'),
        ),
        migrations.CreateModel(
            name='BuyingHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_token', models.CharField(max_length=128)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
