# Generated by Django 3.1 on 2020-09-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200921_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.TextField(choices=[('easy', 'easy'), ('medium', 'medium'), ('advanced', 'advanced'), ('hard', 'hard'), ('extrem', 'extrem')], default='medium'),
        ),
    ]
