# Generated by Django 3.1 on 2020-11-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_supportedlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='training_languages',
            field=models.CharField(default='python', max_length=250),
        ),
    ]
