# Generated by Django 3.1 on 2020-11-21 13:04

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_problem_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Tri'), (1, 'Aléatoire'), (2, 'Recherche'), (3, 'Graphe'), (4, 'Glouton'), (5, 'Programmation dynamique'), (6, 'Manipulation de bits'), (7, 'NP complet'), (8, 'Récursivité'), (9, 'Théorie des jeux'), (10, 'Implémentation'), (11, 'Constructifs'), (12, 'Chaîne de caractères'), (13, 'Géométrie'), (14, 'Mathématiques'), (15, 'Backtracking'), (16, 'Diviser pour Régner')], default='Aléatoire', max_length=40),
        ),
        migrations.CreateModel(
            name='PlanningEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Interview')),
                ('day', models.IntegerField()),
                ('time', models.CharField(max_length=6)),
                ('end_date', models.DateTimeField()),
                ('language', models.CharField(default='Python', max_length=100)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('topics', models.TextField(default='Aléatoire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
