# Generated by Django 3.1 on 2020-11-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201121_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningevent',
            name='end_date',
        ),
    ]
