# Generated by Django 3.1 on 2020-11-30 15:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201123_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='topic1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Tri', 'Tri'), ('Aléatoire', 'Aléatoire'), ('Recherche', 'Recherche'), ('Graphe', 'Graphe'), ('Glouton', 'Glouton'), ('Programmation dynamique', 'Programmation dynamique'), ('Manipulation de bits', 'Manipulation de bits'), ('NP complet', 'NP complet'), ('Récursivité', 'Récursivité'), ('Théorie des jeux', 'Théorie des jeux'), ('Implémentation', 'Implémentation'), ('Constructifs', 'Constructifs'), ('Chaîne de caractères', 'Chaîne de caractères'), ('Géométrie', 'Géométrie'), ('Mathématiques', 'Mathématiques'), ('Backtracking', 'Backtracking'), ('Diviser pour Régner', 'Diviser pour Régner')], default='Aléatoire', max_length=229),
        ),
        migrations.AlterField(
            model_name='problem',
            name='topic2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Tri', 'Tri'), ('Aléatoire', 'Aléatoire'), ('Recherche', 'Recherche'), ('Graphe', 'Graphe'), ('Glouton', 'Glouton'), ('Programmation dynamique', 'Programmation dynamique'), ('Manipulation de bits', 'Manipulation de bits'), ('NP complet', 'NP complet'), ('Récursivité', 'Récursivité'), ('Théorie des jeux', 'Théorie des jeux'), ('Implémentation', 'Implémentation'), ('Constructifs', 'Constructifs'), ('Chaîne de caractères', 'Chaîne de caractères'), ('Géométrie', 'Géométrie'), ('Mathématiques', 'Mathématiques'), ('Backtracking', 'Backtracking'), ('Diviser pour Régner', 'Diviser pour Régner')], default='Aléatoire', max_length=229),
        ),
        migrations.AlterField(
            model_name='problem',
            name='topic3',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Tri', 'Tri'), ('Aléatoire', 'Aléatoire'), ('Recherche', 'Recherche'), ('Graphe', 'Graphe'), ('Glouton', 'Glouton'), ('Programmation dynamique', 'Programmation dynamique'), ('Manipulation de bits', 'Manipulation de bits'), ('NP complet', 'NP complet'), ('Récursivité', 'Récursivité'), ('Théorie des jeux', 'Théorie des jeux'), ('Implémentation', 'Implémentation'), ('Constructifs', 'Constructifs'), ('Chaîne de caractères', 'Chaîne de caractères'), ('Géométrie', 'Géométrie'), ('Mathématiques', 'Mathématiques'), ('Backtracking', 'Backtracking'), ('Diviser pour Régner', 'Diviser pour Régner')], default='Aléatoire', max_length=229),
        ),
    ]
