# Generated by Django 3.1 on 2020-12-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201130_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramHistory',
            new_name='ProblemHistory',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
