# Generated by Django 3.1 on 2020-09-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
