# Generated by Django 3.1 on 2020-08-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200824_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='problem',
            new_name='problemTruc',
        ),
    ]
