# Generated by Django 3.1 on 2020-08-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200824_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='problemTruc',
            new_name='problem',
        ),
    ]
