# Generated by Django 3.1 on 2020-09-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0012_delete_buyinghash'),
        ('core', '0003_auto_20200921_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='price',
        ),
        migrations.AddField(
            model_name='problem',
            name='unit_price',
            field=models.ForeignKey(help_text="When a Problem is bought, we need to know what's the unit price of it. It could be a basic problem or a mini-project (more expensive)", null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe.price'),
        ),
    ]
