# Generated by Django 3.1 on 2020-08-30 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_scheduler', '0002_auto_20200830_1647'),
        ('core', '0004_auto_20200824_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mail_scheduler.companylogo'),
        ),
    ]
