# Generated by Django 3.1 on 2020-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_problem_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='bootcode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
