global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: '1interviewparjour'
    scrape_interval: 5s
    static_configs:
      - targets: ['1interviewparjourjour:8000'] # meant to be run in a docker network
    metrics_path: "/api/v1/observability/metrics"

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
