global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

scrape_configs:

  - job_name: '1interviewparjour'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.1interviewparjour-swarm_1interviewparjour-app'
        type: 'A'
        port: 8000
    metrics_path: '/api/v1/observability/metrics'

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
