# Generated by Django 3.1 on 2020-09-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0003_auto_20200921_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='active',
            field=models.BooleanField(default=True, help_text='If the price is active in Stripe'),
        ),
        migrations.AlterField(
            model_name='price',
            name='billing_scheme',
            field=models.CharField(choices=[('PER_UNIT', 'per_unit'), ('TIERED', 'tiered')], default='PER_UNIT', help_text='Whether its per unit payment or tiered', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('DOLLAR', 'usd'), ('EURO', 'eur'), ('POUND', 'gbp')], default='EURO', help_text='EUR, USD, GBP...', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='livemode',
            field=models.BooleanField(default=False, help_text='If its only for test, then it should be False. Else, True.'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('RECURRING', 'recurring'), ('ONE_TIME', 'one_time')], default='RECURRING', help_text='Is it recurring (every month/every week/...) or is it a one time order ?', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(help_text='The product associated with this price', null=True, on_delete=django.db.models.deletion.CASCADE, to='stripe.product'),
        ),
        migrations.AlterField(
            model_name='price',
            name='recurring_interval',
            field=models.CharField(choices=[('NULL', None), ('DAY', 'day'), ('WEEK', 'week'), ('MONTH', 'month'), ('YEAR', 'year')], default='MONTH', help_text='Type of the recurring interval.', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='recurring_usage_type',
            field=models.CharField(choices=[('NULL', None), ('LICENSED', 'licensed'), ('METERED', 'metered')], default='LICENSED', help_text='Usage type of the recurring payment. For us its only LICENSED.', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='unit_amount',
            field=models.IntegerField(help_text='The price of the product (in cents of the chosen currency. e.g : 699 is 6,99€ in EUR currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', help_text='A short product desc. which will appear in the Stripe Checkout page.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.TextField(default='', help_text='A link to our product image. Either it comes from our S3 bucket (recommended) or left blank to be later completed on the Stripe management dashboard'),
        ),
        migrations.AlterField(
            model_name='product',
            name='livemode',
            field=models.BooleanField(default=False, help_text='If its only for test, then it should be False. Else, True.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product shown in the Stripe Checkout page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SERVICE', 'service'), ('GOOD', 'good')], default='SERVICE', help_text='If its a SERVICE, then it will be a Subscription Stripe object likely to be recurrent. Else, its a GOOD and is a one time Order Stripe object.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(help_text="The Stripe product_id. Something like 'prod_zefaXSszaf...'", max_length=255),
        ),
    ]
