# Generated by Django 3.1 on 2020-09-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0006_auto_20200921_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='recurring_interval_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='price',
            name='stripe_price_id',
            field=models.CharField(editable=False, help_text="The Stripe price_id. Something like 'price_zezgfXSszaf...'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether the product is active or not.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(editable=False, help_text="The Stripe product_id. Something like 'prod_zefaXSszaf...'", max_length=255, null=True),
        ),
    ]
