# Generated by Django 3.1 on 2020-09-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0007_auto_20200921_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='billing_scheme',
            field=models.CharField(choices=[('per_unit', 'per_unit'), ('tiered', 'tiered')], default='per_unit', help_text='Whether its per unit payment or tiered', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('gbp', 'gbp')], default='eur', help_text='EUR, USD, GBP...', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('recurring', 'recurring'), ('one_time', 'one_time')], default='recurring', help_text='Is it recurring (every month/every week/...) or is it a one time order ?', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='recurring_interval',
            field=models.CharField(choices=[(None, None), ('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='month', help_text='Type of the recurring interval.', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='recurring_usage_type',
            field=models.CharField(choices=[(None, None), ('licensed', 'licensed'), ('metered', 'metered')], default='licensed', help_text='Usage type of the recurring payment. For us its only LICENSED.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('service', 'service'), ('good', 'good')], default='service', help_text='If its a SERVICE, then it will be a Subscription Stripe object likely to be recurrent. Else, its a GOOD and is a one time Order Stripe object.', max_length=20),
        ),
    ]
